apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-app
  namespace: argocd
spec:
  project: development
  source:
    repoURL: https://github.com/Elias-Belkheiri/InceptionOfThings
    targetRevision: HEAD
    path: p3/deployment
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
