Vagrant.configure("2") do |config|
  config.vm.define "master" do |master|
      master.vm.box = "spox/ubuntu-arm" 
      master.vm.box_version = "1.0.0"
      master.vm.hostname = 'master'
      master.vm.network "forwarded_port", guest: 80, host: 1234
      master.vm.provision "shell", path: "scripts/server.sh"

      master.vm.provider "vmware_desktop" do |v|
          v.allowlist_verified = true
          v.gui = false
          v.vmx["memsize"] = "1024"
          v.vmx["numvcpus"] = "1"
    end
  end
end
